# Generated by Django 6.0.6 on 2026-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Wholesale Price', max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Retail Price', max_digits=10),
        ),
    ]
