# Generated by Django 6.0.6 on 2026-06-29 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_restocked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
